["404media.co"]
tags = ["news"]
description = """
  404 Media is a journalist-founded digital media company exploring the ways
  technology is shaping–and is shaped by–our world.
  """

["bandcamp.com"]
tags = ["music"]
description = """
  Bandcamp is an online record store and music community where passionate fans
  discover, connect with, and directly support the artists they love.
  """

["bookshop.org"]
tags = ["books", "shops"]
description = """
  Bookshop.org is an online book marketplace launched in January 2020.
  Its stated mission is "to financially support local, independent bookstores."
  """

["codeberg.org"]
tags = ["git forges"]
description = """
  Codeberg is a collaboration platform providing Git hosting and services for
  free and open source software, content and projects.
  """

["gutenberg.org"]
tags = ["books"]
description = """
  Project Gutenberg is a library of over 70,000 public domain eBooks.
  """

["kagi.com"]
tags = ["search engines"]
description = """
  Kagi Inc. is a company created with the mission to humanize the web. Our goal
  is to amplify the web of human knowledge, creativity, and self-expression.
  """

["liberapay.com"]
tags = ["money"]
description = """
  Liberapay is a non-profit recurrent donations platform.
  """

["libro.fm"]
tags = ["books", "shops"]
description = """
  Libro.fm is an employee-owned Social Purpose Corporation that shares profits
  from your audiobook purchases with your chosen bookstore, giving you the
  power to keep money within your local economy.
  """

["lobste.rs"]
tags = ["communities"]
description = """
  Lobsters is a computing-focused community centered around link aggregation
  and discussion
  """

["lwn.net"]
tags = ["news"]
description = """
  LWN.net is a reader-supported news site dedicated to producing the best
  coverage from within the Linux and free software development communities
  """

["maps.earth"]
tags = ["maps"]
description = """
  Open-source maps for everyone, powered by Headway and OpenStreetMap.
  """

["matrix.org"]
tags = ["messaging"]
description = """
  Matrix is a rich ecosystem of clients, servers, bots and application services
  operating on a secure, decentralised, communication network.
  """

["organicmaps.app"]
tags = ["maps"]
description = """
  Organic Maps is a free Android & iOS offline maps app for travelers,
  tourists, hikers, drivers and cyclists based on OpenStreetMap data created by
  the community. It is a privacy-focused, open-source fork of Maps.me app.
  """

["platformer.news"]
tags = ["news"]
description = """
  Platformer is your daily guide to understanding social networks and their
  relationships with the world.
"""

["search.marginalia.nu"]
tags = ["search engines"]
description = """
  Marginalia is an independent DIY search engine that focuses on non-commercial
  content, and attempts to show you sites you perhaps weren't aware of in favor
  of the sort of sites you probably already knew existed.
"""

["signal.org"]
tags = ["messaging"]
description = """
  Signal is an open source encrypted messaging service for instant messaging,
  voice calls, and video calls.
  """

["sourcehut.org"]
tags = ["git forges"]
description = """
  Sourcehut is an open source software development platform.
  """

["standardebooks.org"]
tags = ["books"]
description = """
  Standard Ebooks is a volunteer-driven project that produces new editions of
  public domain ebooks that are lovingly formatted, open source, free of U.S.
  copyright restrictions, and free of cost.
  """

["tucsonpathways.org"]
tags = ["maps"]
description = """
  Finding Safer, Smarter, Quieter Cycling Routes in Tucson, AZ.
  """
